version: '3.7'

networks:
  nodetarimage-network:

services:
  nodetarimage:
    container_name: nodetarimage
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - 5500:5500
    volumes:
      #- ./:/nodetar
      - ./node_modules:/nodetar/node_modules
    command: npm run start:dev
    networks:
      - nodetarimage-network